# Generated by Django 3.0.6 on 2020-05-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seer_app', '0003_auto_20200518_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='Keywords',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
