# Generated by Django 3.0.6 on 2020-05-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seer_app', '0004_auto_20200519_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Status',
            field=models.CharField(choices=[('SUB', 'SUBMITTED'), ('IN_MOD', 'IN MODERATION'), ('MOD', 'MODERATED'), ('ANA', 'ANALYZED'), ('SAV', 'SAVED')], default='SAV', max_length=6),
        ),
        migrations.AlterField(
            model_name='account',
            name='Account_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='Password',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='account',
            name='Username',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='article',
            name='Article_Description',
            field=models.TextField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='article',
            name='Article_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='Author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='Journal',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='Title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='roles',
            name='Role_Description',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='roles',
            name='Role_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='search',
            name='Keywords',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='Search_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='user',
            name='F_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='L_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
