# Generated by Django 3.0.6 on 2020-05-19 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seer_app', '0006_auto_20200519_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Publication_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Birth_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birth Date'),
        ),
    ]
