# Generated by Django 3.0.6 on 2020-06-01 03:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seer_app', '0008_auto_20200520_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountroles',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roles',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='search',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='Account_ID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Account ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seer_app.User', verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='Username',
            field=models.CharField(default='', max_length=40, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='accountroles',
            name='Account_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seer_app.Account', verbose_name='Account ID'),
        ),
        migrations.AlterField(
            model_name='accountroles',
            name='Role_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seer_app.Roles', verbose_name='Role ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Article_Description',
            field=models.TextField(default='', max_length=800, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Article_ID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Article ID'),
        ),
        migrations.AlterField(
            model_name='article',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seer_app.User', verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='Role_Description',
            field=models.CharField(default='', max_length=40, verbose_name='Role Description'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='Role_ID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Role ID'),
        ),
        migrations.AlterField(
            model_name='search',
            name='Article_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seer_app.Article', verbose_name='Article ID'),
        ),
        migrations.AlterField(
            model_name='search',
            name='Search_ID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Search ID'),
        ),
        migrations.AlterField(
            model_name='search',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seer_app.User', verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='F_name',
            field=models.CharField(default='', max_length=40, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='L_name',
            field=models.CharField(default='', max_length=40, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_ID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='User ID'),
        ),
    ]
