# Generated by Django 3.0.6 on 2020-06-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seer_app', '0010_auto_20200601_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Status',
            field=models.CharField(choices=[('SUB', 'Submitted'), ('IN_MOD', 'In Moderation'), ('MOD', 'Moderated'), ('IN_ANA', 'In Analysis'), ('ANA', 'Analyzed')], default='SUB', max_length=6),
        ),
    ]
